CREATE TABLE `CartItems` (
    `ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `ProductID` BIGINT UNSIGNED,
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
ALTER TABLE `CartItems`
ADD CONSTRAINT `FKCartItemsProducts` FOREIGN KEY (`ProductID`) REFERENCES `Products` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;