CREATE TABLE `Products` (
    `ID` BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `Name` VARCHAR(255),
    `Image` VARCHAR(255),
    `Format` VARCHAR(255),
    `Price` DECIMAL(15, 2),
    `CreatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `UpdatedAt` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);