@serverURL = http://localhost:8080

###
GET {{serverURL}}/api/carts
Accept: application/json

###
POST {{serverURL}}/api/carts
Content-Type: application/json

{
  "productID": 1,
  "quanitity": 1
}

###
DELETE {{serverURL}}/api/carts/2
Content-Type: application/json
