root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "tmp/app"
cmd = "make build"
delay = 1000
exclude_dir = ["api", "db", "docs", "test"]
exclude_file = [
    ".dockerignore",
    ".env.example",
    ".envrc",
    ".gitignore",
    ".golangci.yaml",
    "compose.yaml",
    "Dockerfile",
    "flake.lock",
    "flake.nix",
    "Makefile",
]
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = [".env"]
kill_delay = 500
log = "air.log"
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = true
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = true
time = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
