name: locavest

volumes:
  db-persistence: {}

networks:
  net:
    driver: bridge

services:
  backend:
    container_name: locavest_backend
    build: .
    networks: [net]
    restart: unless-stopped
    ports: ["80:${API_PORT}"]
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env]

  db:
    container_name: locavest_db
    image: mariadb:11.3.2-jammy
    command: ['mariadbd', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: unless-stopped
    ports: [5432:3306]
    networks: [net]
    volumes:
      - db-persistence:/var/lib/mysql
      - ${PWD}/db/migrations:/docker-entrypoint-initdb.d
    env_file: [.env]
    environment:
      - MARIADB_DATABASE=${DB_SCHEMA}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
